### PR TITLE
Position after website redirection fixed

### PR DESCRIPTION
**Pull request by Dillonsd**
The webpage scrolls to the top after redirecting. Previously the scroll position from one tab was passed on to the next.

### CODE REVIEW

**Review by JaydenBischoff — COMMENTED** [review]
I tried running it from my machine but I noticed that when you go to a different tab it still loads part way down the screen. I'm not sure if this is just an issue from my end though.

**Comment by JensVarughese** [comment]
> I tried running it from my machine but I noticed that when you go to a different tab it still loads part way down the screen. I'm not sure if this is just an issue from my end though.

I think its just on your end. I tried it on my system and it redirects to the top of the screen.

**Review by JensVarughese — APPROVED** [review]
Looks good from what I see, but is there a reason you changed the version of google and karma?

**Comment by Dillonsd** [comment]
> Looks good from what I see, but is there a reason you changed the version of google and karma?

I should've put this in the description, my bad. I was unable to get the project to run without calling npm install, I think it upgraded the version of some packages.

**Comment by JensVarughese** [comment]
> > Looks good from what I see, but is there a reason you changed the version of google and karma?
> 
> I should've put this in the description, my bad. I was unable to get the project to run without calling npm install, I think it upgraded the version of some packages.

No worries it wont really change much anyways. Just wait for Jayden to approve this and then you can sqaush and merge.

**Review by JaydenBischoff — APPROVED** [review]

**Pull request merged**
